from __future__ import annotations

import argparse
import hashlib
import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


MANIFEST_BEGIN = "=== TASKMASTER_DERIVED_INPUT_MANIFEST_JSON_BEGIN ==="
MANIFEST_END = "=== TASKMASTER_DERIVED_INPUT_MANIFEST_JSON_END ==="


@dataclass(frozen=True)
class SourceInfo:
    path: str
    exists: bool
    size_bytes: int | None
    mtime_utc: str | None
    sha256: str | None


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _utc_iso(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).replace(microsecond=0).isoformat()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _collect_sources(repo_root: Path, sources: Iterable[str]) -> list[SourceInfo]:
    infos: list[SourceInfo] = []
    for rel in sources:
        p = (repo_root / rel).resolve()
        if not p.exists():
            infos.append(
                SourceInfo(
                    path=rel.replace("\\", "/"),
                    exists=False,
                    size_bytes=None,
                    mtime_utc=None,
                    sha256=None,
                )
            )
            continue

        st = p.stat()
        infos.append(
            SourceInfo(
                path=rel.replace("\\", "/"),
                exists=True,
                size_bytes=int(st.st_size),
                mtime_utc=_utc_iso(datetime.fromtimestamp(st.st_mtime, tz=timezone.utc)),
                sha256=_sha256_file(p),
            )
        )
    return infos


def _default_sources() -> list[str]:
    return [
        "project-context.md",
        "docs/prd/PRD-NEWROUGE-GAME-0001.md",
        "docs/gdd/GDD-NEWROUGE-V1.md",
        "docs/prd/SSOT-LOCKS-NEWROUGE-V1.md",
        "docs/prd/MECHANICS-EDGE-CASES-SSOT-NEWROUGE-V1.md",
        "docs/architecture/overlays/PRD-NEWROUGE-GAME-0001/08/ACCEPTANCE_CHECKLIST.md",
        "docs/architecture/overlays/PRD-NEWROUGE-GAME-0001/08/_index.md",
        "docs/adr/ADR-0032-save-resume-determinism.md",
        "docs/adr/ADR-0033-card-identity-and-forms.md",
    ]


def _read_text_utf8(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write_text_utf8(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _default_log_dir(repo_root: Path) -> Path:
    date = datetime.now(tz=timezone.utc).date().isoformat()
    return repo_root / "logs" / "ci" / date / "taskmaster-prd-input"


def _write_log_json(log_dir: Path, file_name: str, payload: dict) -> Path:
    log_dir.mkdir(parents=True, exist_ok=True)
    out = log_dir / file_name
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8", newline="\n")
    return out


def _render_manifest(manifest: dict) -> str:
    return "\n".join(
        [
            MANIFEST_BEGIN,
            json.dumps(manifest, ensure_ascii=False, indent=2),
            MANIFEST_END,
            "",
        ]
    )


def _render_sources_table(sources: list[SourceInfo]) -> str:
    lines = ["Sources (SSoT anchors; do not edit this file by hand):"]
    for s in sources:
        if not s.exists:
            lines.append(f"- MISSING: {s.path}")
            continue
        lines.append(f"- {s.path} | mtime_utc={s.mtime_utc} | sha256={s.sha256} | bytes={s.size_bytes}")
    return "\n".join(lines) + "\n"


def write_prd_input(repo_root: Path, output_rel: str, sources_rel: list[str], log_dir: Path | None) -> Path:
    sources = _collect_sources(repo_root, sources_rel)
    missing = [s.path for s in sources if not s.exists]
    if missing:
        raise FileNotFoundError(f"Missing source files: {', '.join(missing)}")

    generated_at_utc = _utc_iso(datetime.now(tz=timezone.utc))
    manifest = {
        "schema": "taskmaster-derived-prd-input/v1",
        "project_root": str(repo_root).replace("\\", "/"),
        "generated_at_utc": generated_at_utc,
        "output": output_rel.replace("\\", "/"),
        "sources": [s.__dict__ for s in sources],
    }

    owner = os.environ.get("USERNAME", "unknown")
    header = "\n".join(
        [
            "NewRouge v1 - Taskmaster PRD Input (Derived; AUTO-GENERATED)",
            "",
            f"Owner: {owner}",
            f"Generated At (UTC): {generated_at_utc}",
            "Encoding: UTF-8",
            "",
            "IMPORTANT",
            "1) This file is a DERIVED INPUT for Taskmaster. It is not the SSoT.",
            "2) Canonical SSoT lives in docs/** and project-context.md (see Sources below).",
            "3) If any conflicts exist, follow Accepted ADRs and the SSoT markdown files; then regenerate this file.",
            "",
            _render_sources_table(sources).rstrip(),
            "",
        ]
    )

    parts: list[str] = [_render_manifest(manifest), header]
    for rel in sources_rel:
        p = repo_root / rel
        content = _read_text_utf8(p)
        parts.append(f"===== BEGIN SOURCE: {rel.replace('\\', '/')} =====\n")
        parts.append(content.rstrip("\n") + "\n")
        parts.append(f"===== END SOURCE: {rel.replace('\\', '/')} =====\n\n")

    out_path = repo_root / output_rel
    _write_text_utf8(out_path, "".join(parts).rstrip() + "\n")

    if log_dir is not None:
        _write_log_json(
            log_dir,
            "write.json",
            {
                "ok": True,
                "action": "write",
                "generated_at_utc": generated_at_utc,
                "output": output_rel.replace("\\", "/"),
                "sources": [s.__dict__ for s in sources],
            },
        )

    return out_path


def _extract_manifest(text: str) -> dict:
    begin = text.find(MANIFEST_BEGIN)
    end = text.find(MANIFEST_END)
    if begin == -1 or end == -1 or end <= begin:
        raise ValueError("Missing manifest block in output file.")

    json_start = begin + len(MANIFEST_BEGIN)
    json_blob = text[json_start:end].strip()
    if not json_blob:
        raise ValueError("Manifest JSON is empty.")
    return json.loads(json_blob)


def check_prd_input(repo_root: Path, output_rel: str, log_dir: Path | None) -> int:
    out_path = repo_root / output_rel
    if not out_path.exists():
        if log_dir is not None:
            _write_log_json(log_dir, "check.json", {"ok": False, "reason": "missing_output", "output": output_rel})
        return 2

    try:
        manifest = _extract_manifest(_read_text_utf8(out_path))
    except Exception as e:
        if log_dir is not None:
            _write_log_json(
                log_dir,
                "check.json",
                {"ok": False, "reason": "invalid_manifest", "output": output_rel, "error": str(e)},
            )
        return 2

    sources = manifest.get("sources", [])
    if not isinstance(sources, list) or not sources:
        if log_dir is not None:
            _write_log_json(log_dir, "check.json", {"ok": False, "reason": "missing_sources_in_manifest"})
        return 2

    mismatches: list[dict] = []
    missing: list[str] = []
    for s in sources:
        rel = s.get("path")
        if not isinstance(rel, str):
            mismatches.append({"path": rel, "reason": "invalid_path_type"})
            continue
        p = repo_root / rel
        if not p.exists():
            missing.append(rel)
            continue
        actual_sha = _sha256_file(p)
        expected_sha = s.get("sha256")
        if actual_sha != expected_sha:
            mismatches.append(
                {
                    "path": rel,
                    "reason": "sha256_mismatch",
                    "expected_sha256": expected_sha,
                    "actual_sha256": actual_sha,
                }
            )

    ok = not missing and not mismatches
    if log_dir is not None:
        _write_log_json(
            log_dir,
            "check.json",
            {
                "ok": ok,
                "output": output_rel.replace("\\", "/"),
                "missing_sources": missing,
                "mismatches": mismatches,
            },
        )
    return 0 if ok else 2


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Generate/check .taskmaster/docs/prd.txt as a derived Taskmaster input with sources/mtime/sha256.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    w = sub.add_parser("write", help="Write (regenerate) the derived PRD input file.")
    w.add_argument("--output", default=".taskmaster/docs/prd.txt")
    w.add_argument("--source", action="append", default=None, help="Relative path; can be repeated.")
    w.add_argument("--log-dir", default=None, help="Optional; default is logs/ci/<date>/taskmaster-prd-input.")

    c = sub.add_parser("check", help="Check whether the derived PRD input is up to date with its sources.")
    c.add_argument("--output", default=".taskmaster/docs/prd.txt")
    c.add_argument("--log-dir", default=None, help="Optional; default is logs/ci/<date>/taskmaster-prd-input.")
    return p


def main() -> int:
    args = _build_parser().parse_args()
    repo_root = _repo_root()

    log_dir = Path(args.log_dir) if args.log_dir else _default_log_dir(repo_root)

    if args.cmd == "write":
        sources_rel = args.source if args.source is not None else _default_sources()
        write_prd_input(repo_root, args.output, sources_rel, log_dir=log_dir)
        return 0

    if args.cmd == "check":
        return check_prd_input(repo_root, args.output, log_dir=log_dir)

    raise RuntimeError(f"Unknown command: {args.cmd}")


if __name__ == "__main__":
    raise SystemExit(main())
