using System;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using FluentAssertions;
using Xunit;

namespace Game.Core.Tests.Tasks;

public sealed class Task1DotnetRestoreLockfileTests
{
    private static readonly SemaphoreSlim TestGate = new(1, 1);
    private static readonly TimeSpan RestoreTimeout = TimeSpan.FromSeconds(120);

    // ACC:T1.9
    // ACC:T1.10
    [Fact]
    public async Task ShouldGeneratePackagesLockFile_WhenMissingBeforeDotnetRestore()
    {
        var repoRoot = FindRepoRoot();
        var lockfilePath = Path.Combine(repoRoot, "packages.lock.json");
        var backupPath = lockfilePath + ".task1.backup";
        var existedInitially = File.Exists(lockfilePath);

        await TestGate.WaitAsync();
        try
        {
            if (File.Exists(backupPath))
            {
                File.Delete(backupPath);
            }

            if (existedInitially)
            {
                File.Copy(lockfilePath, backupPath, overwrite: true);
                File.Delete(lockfilePath);
            }

            File.Exists(lockfilePath).Should().BeFalse("the test precondition requires a missing lock file");

            var restore = await RunDotnetRestoreAsync(repoRoot);

            restore.ExitCode.Should().Be(0, restore.CombinedOutput);
            File.Exists(lockfilePath).Should().BeTrue("dotnet restore must generate packages.lock.json when it is missing");
        }
        finally
        {
            if (existedInitially && File.Exists(backupPath))
            {
                File.Copy(backupPath, lockfilePath, overwrite: true);
                File.Delete(backupPath);
            }
            else if (!existedInitially && File.Exists(lockfilePath))
            {
                File.Delete(lockfilePath);
            }

            TestGate.Release();
        }
    }

    [Fact]
    public async Task ShouldKeepPackagesLockFile_WhenItAlreadyExistsAfterDotnetRestore()
    {
        await TestGate.WaitAsync();
        try
        {
            var repoRoot = FindRepoRoot();
            var lockfilePath = Path.Combine(repoRoot, "packages.lock.json");

            File.Exists(lockfilePath).Should().BeTrue("this negative-path check verifies restore does not remove an existing lock file");

            var restore = await RunDotnetRestoreAsync(repoRoot);

            restore.ExitCode.Should().Be(0, restore.CombinedOutput);
            File.Exists(lockfilePath).Should().BeTrue("dotnet restore must not delete an existing packages.lock.json");
            new FileInfo(lockfilePath).Length.Should().BeGreaterThan(0, "the existing lock file should remain a non-empty artifact");
        }
        finally
        {
            TestGate.Release();
        }
    }

    // ACC:T1.15
    [Fact]
    public async Task ShouldPersistFullStdoutToDailyEnvEvidenceFile_WhenDotnetRestoreRuns()
    {
        var repoRoot = FindRepoRoot();
        var dateSegment = DateTime.UtcNow.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        var evidencePath = Path.Combine(repoRoot, "logs", "ci", dateSegment, "env-evidence", "dotnet-restore.txt");
        var taskJsonPath = Path.Combine(repoRoot, "logs", "ci", dateSegment, "task-0001.json");

        await TestGate.WaitAsync();
        try
        {
            var restore = await RunDotnetRestoreAsync(repoRoot);

            restore.ExitCode.Should().Be(0, restore.CombinedOutput);
            restore.StdOut.Should().NotBeNullOrWhiteSpace("acceptance requires persisting full stdout");
            File.Exists(evidencePath).Should().BeTrue(
                "acceptance preflight must persist stdout to logs/ci/<YYYY-MM-DD>/env-evidence/dotnet-restore.txt before Task1 tests run");

            var persisted = File.ReadAllText(evidencePath);
            var expectedPersisted = BuildPersistedRestoreEvidence(restore);
            NormalizeLineEndings(persisted).Should().Be(
                NormalizeLineEndings(expectedPersisted),
                "the evidence file must contain the same stdout/stderr stream shape produced by preflight");

            File.Exists(taskJsonPath).Should().BeTrue("task-0001.json must be generated by acceptance preflight");
            ValidateDotnetRestoreEvidence(taskJsonPath, repoRoot);
        }
        finally
        {
            TestGate.Release();
        }
    }

    [Theory]
    [InlineData("{\"dotnet_restore\":{\"exit_code\":0,\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/dotnet-restore.txt\"}}", "dotnet_restore.command is required")]
    [InlineData("{\"dotnet_restore\":{\"command\":\"dotnet restore .\\\\NewRouge.sln\",\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/dotnet-restore.txt\"}}", "dotnet_restore.exit_code is required")]
    [InlineData("{\"dotnet_restore\":{\"command\":\"dotnet restore .\\\\NewRouge.sln\",\"exit_code\":0}}", "dotnet_restore.evidence_file is required")]
    public void ShouldFailDotnetRestoreValidation_WhenRequiredKeyIsMissing(string payload, string expectedError)
    {
        var tempRoot = Path.Combine(Path.GetTempPath(), "newrouge-task1-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempRoot);

        try
        {
            File.WriteAllText(Path.Combine(tempRoot, "NewRouge.sln"), "Microsoft Visual Studio Solution File, Format Version 12.00");
            var evidenceDir = Path.Combine(tempRoot, "logs", "ci", "2026-02-15", "env-evidence");
            Directory.CreateDirectory(evidenceDir);
            File.WriteAllText(Path.Combine(evidenceDir, "dotnet-restore.txt"), "ok");

            var taskJsonPath = Path.Combine(tempRoot, "task-0001.json");
            File.WriteAllText(taskJsonPath, payload, Encoding.UTF8);

            Action act = () => ValidateDotnetRestoreEvidence(taskJsonPath, tempRoot);
            act.Should().Throw<Exception>().Where(ex => ex.Message.Contains(expectedError, StringComparison.OrdinalIgnoreCase));
        }
        finally
        {
            if (Directory.Exists(tempRoot))
            {
                Directory.Delete(tempRoot, recursive: true);
            }
        }
    }

    [Fact]
    public void ShouldFailDotnetRestoreValidation_WhenRestoreTargetIsNotNewRougeSln()
    {
        var tempRoot = Path.Combine(Path.GetTempPath(), "newrouge-task1-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempRoot);

        try
        {
            File.WriteAllText(Path.Combine(tempRoot, "NewRouge.sln"), "Microsoft Visual Studio Solution File, Format Version 12.00");
            var evidenceDir = Path.Combine(tempRoot, "logs", "ci", "2026-02-15", "env-evidence");
            Directory.CreateDirectory(evidenceDir);
            File.WriteAllText(Path.Combine(evidenceDir, "dotnet-restore.txt"), "ok");

            var payload = "{\"dotnet_restore\":{\"command\":\"dotnet restore .\\\\Other.sln\",\"exit_code\":0,\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/dotnet-restore.txt\"}}";
            var taskJsonPath = Path.Combine(tempRoot, "task-0001.json");
            File.WriteAllText(taskJsonPath, payload, Encoding.UTF8);

            Action act = () => ValidateDotnetRestoreEvidence(taskJsonPath, tempRoot);
            act.Should().Throw<Exception>().Where(ex => ex.Message.Contains("NewRouge.sln", StringComparison.OrdinalIgnoreCase));
        }
        finally
        {
            if (Directory.Exists(tempRoot))
            {
                Directory.Delete(tempRoot, recursive: true);
            }
        }
    }

    [Fact]
    public void ShouldFailDotnetRestoreValidation_WhenExitCodeIsNonZero()
    {
        var tempRoot = Path.Combine(Path.GetTempPath(), "newrouge-task1-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempRoot);

        try
        {
            File.WriteAllText(Path.Combine(tempRoot, "NewRouge.sln"), "Microsoft Visual Studio Solution File, Format Version 12.00");
            var evidenceDir = Path.Combine(tempRoot, "logs", "ci", "2026-02-15", "env-evidence");
            Directory.CreateDirectory(evidenceDir);
            File.WriteAllText(Path.Combine(evidenceDir, "dotnet-restore.txt"), "restore failed");

            var payload = "{\"dotnet_restore\":{\"command\":\"dotnet restore .\\\\NewRouge.sln\",\"exit_code\":1,\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/dotnet-restore.txt\"}}";
            var taskJsonPath = Path.Combine(tempRoot, "task-0001.json");
            File.WriteAllText(taskJsonPath, payload, Encoding.UTF8);

            Action act = () => ValidateDotnetRestoreEvidence(taskJsonPath, tempRoot);
            act.Should().Throw<Exception>().Where(ex => ex.Message.Contains("must succeed", StringComparison.OrdinalIgnoreCase));
        }
        finally
        {
            if (Directory.Exists(tempRoot))
            {
                Directory.Delete(tempRoot, recursive: true);
            }
        }
    }

    // ACC:T1.16
    [Fact]
    public void ShouldFailDotnetRestoreValidation_WhenNewRougeSolutionFileIsMissing()
    {
        var tempRoot = Path.Combine(Path.GetTempPath(), "newrouge-task1-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempRoot);

        try
        {
            var evidenceDir = Path.Combine(tempRoot, "logs", "ci", "2026-02-15", "env-evidence");
            Directory.CreateDirectory(evidenceDir);
            File.WriteAllText(Path.Combine(evidenceDir, "dotnet-restore.txt"), "restore ok");

            var payload = "{\"dotnet_restore\":{\"command\":\"dotnet restore .\\\\NewRouge.sln\",\"exit_code\":0,\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/dotnet-restore.txt\"}}";
            var taskJsonPath = Path.Combine(tempRoot, "task-0001.json");
            File.WriteAllText(taskJsonPath, payload, Encoding.UTF8);

            Action act = () => ValidateDotnetRestoreEvidence(taskJsonPath, tempRoot);
            act.Should().Throw<Exception>().Where(ex => ex.Message.Contains("NewRouge.sln", StringComparison.OrdinalIgnoreCase));
        }
        finally
        {
            if (Directory.Exists(tempRoot))
            {
                Directory.Delete(tempRoot, recursive: true);
            }
        }
    }

    [Theory]
    [InlineData("dotnet restore .\\NewRouge.sln", true)]
    [InlineData("dotnet restore ./NewRouge.sln", true)]
    [InlineData("dotnet restore \"C:\\repo\\NewRouge.sln\" --verbosity minimal", true)]
    [InlineData("dotnet restore .\\Other.sln", false)]
    [InlineData("dotnet test .\\NewRouge.sln", false)]
    public void ShouldValidateSemanticEquivalentRestoreCommand_WhenCommandVariantChanges(string command, bool expected)
    {
        IsSemanticEquivalentRestoreToNewRouge(command).Should().Be(expected);
    }

    private static string FindRepoRoot()
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current is not null)
        {
            if (File.Exists(Path.Combine(current.FullName, "NewRouge.sln")))
            {
                return current.FullName;
            }

            current = current.Parent;
        }

        throw new InvalidOperationException("Unable to locate repository root containing NewRouge.sln.");
    }

    private static async Task<DotnetRestoreResult> RunDotnetRestoreAsync(string repoRoot)
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = "dotnet",
            Arguments = "restore .\\NewRouge.sln",
            WorkingDirectory = repoRoot,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            StandardOutputEncoding = Encoding.UTF8,
            StandardErrorEncoding = Encoding.UTF8,
            CreateNoWindow = true,
        };

        using var process = Process.Start(startInfo);
        process.Should().NotBeNull("dotnet CLI must be available to execute restore");

        var stdOutTask = process!.StandardOutput.ReadToEndAsync();
        var stdErrTask = process.StandardError.ReadToEndAsync();

        var waitTask = process.WaitForExitAsync();
        var completed = await Task.WhenAny(waitTask, Task.Delay(RestoreTimeout));
        if (completed != waitTask)
        {
            var killError = string.Empty;
            try
            {
                if (!process.HasExited)
                {
                    process.Kill(entireProcessTree: true);
                }
            }
            catch (Exception ex)
            {
                killError = ex.Message;
            }

            await Task.WhenAny(process.WaitForExitAsync(), Task.Delay(TimeSpan.FromSeconds(5)));
            var timeoutStdOut = await ReadTaskWithTimeoutAsync(stdOutTask, TimeSpan.FromSeconds(2), "<stdout unavailable>");
            var timeoutStdErr = await ReadTaskWithTimeoutAsync(stdErrTask, TimeSpan.FromSeconds(2), "<stderr unavailable>");
            var timeoutMessage = $"dotnet restore timeout after {RestoreTimeout.TotalSeconds:0}s";
            if (!string.IsNullOrWhiteSpace(killError))
            {
                timeoutMessage += $"; kill error: {killError}";
            }

            return new DotnetRestoreResult(-1, timeoutStdOut, string.Concat(timeoutStdErr, Environment.NewLine, timeoutMessage));
        }

        var stdOut = await ReadTaskWithTimeoutAsync(stdOutTask, TimeSpan.FromSeconds(5), "<stdout read timeout>");
        var stdErr = await ReadTaskWithTimeoutAsync(stdErrTask, TimeSpan.FromSeconds(5), "<stderr read timeout>");
        return new DotnetRestoreResult(process.ExitCode, stdOut, stdErr);
    }

    private static async Task<string> ReadTaskWithTimeoutAsync(Task<string> readTask, TimeSpan timeout, string fallback)
    {
        var completed = await Task.WhenAny(readTask, Task.Delay(timeout));
        if (completed == readTask)
        {
            return await readTask;
        }

        return fallback;
    }

    private static void ValidateDotnetRestoreEvidence(string taskJsonPath, string repoRoot)
    {
        File.Exists(taskJsonPath).Should().BeTrue("task-0001.json must exist for dotnet_restore evidence mapping");
        var solutionPath = Path.Combine(repoRoot, "NewRouge.sln");
        File.Exists(solutionPath).Should().BeTrue("NewRouge.sln must exist in repository workspace for Task1 restore acceptance");

        using var document = JsonDocument.Parse(File.ReadAllText(taskJsonPath));
        var root = document.RootElement;

        root.TryGetProperty("dotnet_restore", out var dotnetRestore).Should().BeTrue("task-0001.json must include dotnet_restore section");
        dotnetRestore.TryGetProperty("command", out var command).Should().BeTrue("dotnet_restore.command is required");
        dotnetRestore.TryGetProperty("exit_code", out var exitCode).Should().BeTrue("dotnet_restore.exit_code is required");
        dotnetRestore.TryGetProperty("evidence_file", out var evidenceFile).Should().BeTrue("dotnet_restore.evidence_file is required");

        var commandValue = command.GetString();
        IsSemanticEquivalentRestoreToNewRouge(commandValue).Should().BeTrue(
            "dotnet_restore.command must semantically target NewRouge.sln using dotnet restore");
        exitCode.GetInt32().Should().Be(0, "dotnet restore must succeed for acceptance evidence");

        var evidenceRelativePath = evidenceFile.GetString();
        evidenceRelativePath.Should().NotBeNullOrWhiteSpace("dotnet_restore.evidence_file must be a relative artifact path");
        var evidenceAbsolutePath = Path.Combine(repoRoot, evidenceRelativePath!.Replace("/", Path.DirectorySeparatorChar.ToString()));
        File.Exists(evidenceAbsolutePath).Should().BeTrue("dotnet_restore.evidence_file must point to an existing artifact file");
        File.ReadAllText(evidenceAbsolutePath).Should().NotBeNullOrWhiteSpace("dotnet restore evidence content must not be empty");
    }

    private static bool IsSemanticEquivalentRestoreToNewRouge(string? command)
    {
        if (string.IsNullOrWhiteSpace(command))
        {
            return false;
        }

        var tokens = TokenizeCommand(command);
        if (tokens.Count < 3)
        {
            return false;
        }

        var executable = tokens[0].Replace("\"", string.Empty).Trim();
        var verb = tokens[1].Replace("\"", string.Empty).Trim();
        if (!executable.EndsWith("dotnet", StringComparison.OrdinalIgnoreCase) &&
            !executable.EndsWith("dotnet.exe", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        if (!string.Equals(verb, "restore", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        foreach (var token in tokens.Skip(2))
        {
            var cleaned = token.Replace("\"", string.Empty).Trim();
            if (!cleaned.EndsWith(".sln", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var fileName = Path.GetFileName(cleaned.Replace("/", "\\"));
            return string.Equals(fileName, "NewRouge.sln", StringComparison.OrdinalIgnoreCase);
        }

        return false;
    }

    private static List<string> TokenizeCommand(string command)
    {
        var tokens = new List<string>();
        var current = new StringBuilder();
        var inQuotes = false;

        foreach (var ch in command)
        {
            if (ch == '"')
            {
                inQuotes = !inQuotes;
                current.Append(ch);
                continue;
            }

            if (char.IsWhiteSpace(ch) && !inQuotes)
            {
                if (current.Length > 0)
                {
                    tokens.Add(current.ToString());
                    current.Clear();
                }

                continue;
            }

            current.Append(ch);
        }

        if (current.Length > 0)
        {
            tokens.Add(current.ToString());
        }

        return tokens;
    }

    private static string BuildPersistedRestoreEvidence(DotnetRestoreResult restore)
    {
        if (string.IsNullOrEmpty(restore.StdErr))
        {
            return restore.StdOut;
        }

        return restore.StdOut + "\n" + restore.StdErr;
    }

    private static string NormalizeLineEndings(string value)
    {
        return value.Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private sealed record DotnetRestoreResult(int ExitCode, string StdOut, string StdErr)
    {
        public string CombinedOutput => string.Concat(StdOut, Environment.NewLine, StdErr);
    }
}
