using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FluentAssertions;
using Xunit;

namespace Game.Core.Tests.Tasks;

public sealed class Task1ToolchainVersionChecksTests
{
    private static readonly TimeSpan CommandTimeout = TimeSpan.FromSeconds(20);

    // ACC:T1.4
    // ACC:T1.5
    // ACC:T1.7
    [Fact]
    public async Task ShouldReportGodot451_WhenRunningVersionCommands()
    {
        var godotBinPath = Environment.GetEnvironmentVariable("GODOT_BIN");
        godotBinPath.Should().NotBeNullOrWhiteSpace("GODOT_BIN must be set to the pinned Godot executable path");
        ArgumentNullException.ThrowIfNull(godotBinPath);
        File.Exists(godotBinPath!).Should().BeTrue("GODOT_BIN should point to an existing executable file");

        var godotExeName = Path.GetFileName(godotBinPath);
        var godotExeDirectory = Path.GetDirectoryName(godotBinPath);

        Path.IsPathRooted(godotBinPath).Should().BeTrue("GODOT_BIN must be an absolute path on Windows");
        godotExeName.Should().NotBeNullOrWhiteSpace("GODOT_BIN must include executable file name");
        godotExeDirectory.Should().NotBeNullOrWhiteSpace("GODOT_BIN must include executable directory");
        ArgumentNullException.ThrowIfNull(godotExeName);
        ArgumentNullException.ThrowIfNull(godotExeDirectory);
        ContainsToken(godotExeName, "mono").Should().BeTrue("GODOT_BIN must target Godot .NET (mono) binary");
        ContainsToken(godotExeName, "console").Should().BeTrue("GODOT_BIN must target Godot console binary");

        var godotFromEnvBin = await RunProcessAsync(godotBinPath, "--version");
        var godotFromPath = await RunProcessAsync(
            "powershell",
            "-NoProfile -ExecutionPolicy Bypass -Command \"godot --version\"",
            prependPath: godotExeDirectory);

        godotFromEnvBin.ExitCode.Should().Be(0, godotFromEnvBin.DebugOutput);

        OutputContainsToken(godotFromEnvBin.StdOut, "4.5.1").Should().BeTrue(
            "& $env:GODOT_BIN --version stdout must include 4.5.1");
        OutputContainsToken(godotFromEnvBin.StdOut, "mono").Should().BeTrue(
            "& $env:GODOT_BIN --version stdout must prove mono flavor for .NET build");
        if (godotFromPath.ExitCode == 0)
        {
            OutputContainsToken(godotFromPath.StdOut, "4.5.1").Should().BeTrue(
                "when PATH is configured, godot --version stdout must include 4.5.1");
            OutputContainsToken(godotFromPath.StdOut, "mono").Should().BeTrue(
                "when PATH is configured, godot --version stdout must prove mono flavor for .NET build");
        }

        var repoRoot = FindRepoRoot();
        var dateSegment = DateTime.UtcNow.ToString("yyyy-MM-dd");
        var taskJsonPath = Path.Combine(repoRoot, "logs", "ci", dateSegment, "task-0001.json");

        File.Exists(taskJsonPath).Should().BeTrue("task-0001.json must be generated by acceptance preflight before Task1 tests run");
        ValidateGodotCommandEvidence(taskJsonPath, repoRoot, godotBinPath);
    }

    // ACC:T1.8
    [Fact]
    public async Task ShouldReportDotnet8_WhenRunningDotnetVersion()
    {
        var dotnetVersion = await RunProcessAsync("dotnet", "--version");
        var dotnetSdks = await RunProcessAsync("dotnet", "--list-sdks");

        IsValidDotnetVersionCommand(dotnetVersion.ExitCode, dotnetVersion.StdOut).Should().BeTrue(dotnetVersion.DebugOutput);
        HasDotnet8Sdk(dotnetSdks.ExitCode, dotnetSdks.StdOut).Should().BeTrue(dotnetSdks.DebugOutput);

        var repoRoot = FindRepoRoot();
        var dateSegment = DateTime.UtcNow.ToString("yyyy-MM-dd");
        var taskJsonPath = Path.Combine(repoRoot, "logs", "ci", dateSegment, "task-0001.json");
        File.Exists(taskJsonPath).Should().BeTrue("task-0001.json must be generated by acceptance preflight before Task1 tests run");
        ValidateDotnetSdkEvidence(taskJsonPath, repoRoot);
    }

    [Theory]
    [InlineData("4.5.1.stable.official", "4.5.1", true)]
    [InlineData("Godot Engine v4.5.1.stable", "4.5.1", true)]
    [InlineData("4.5.0.stable.official", "4.5.1", false)]
    public void ShouldDetectExpectedVersionToken_WhenOutputIsParsed(
        string output,
        string token,
        bool expected)
    {
        OutputContainsToken(output, token).Should().Be(expected);
    }

    [Theory]
    [InlineData("8.0.204", "8.0.204")]
    [InlineData("\r\n8.0.300\r\n", "8.0.300")]
    [InlineData("\r\n \r\n9.0.100\r\n", "9.0.100")]
    public void ShouldReturnFirstNonEmptyLine_WhenOutputContainsNoise(string input, string expected)
    {
        GetFirstNonEmptyLine(input).Should().Be(expected);
    }

    [Theory]
    [InlineData(0, "Godot Engine v4.5.1.stable.mono", true)]
    [InlineData(1, "Godot Engine v4.5.1.stable.mono", false)]
    [InlineData(0, "Godot Engine v4.5.0.stable.mono", false)]
    [InlineData(0, "", false)]
    public void ShouldValidateGodotCommandEvidence_WhenExitCodeAndOutputChange(int exitCode, string output, bool expected)
    {
        IsValidGodotCommandEvidence(exitCode, output).Should().Be(expected);
    }

    [Theory]
    [InlineData(0, "8.0.418", true)]
    [InlineData(0, "7.0.404", false)]
    [InlineData(0, "9.0.100", false)]
    [InlineData(1, "8.0.418", false)]
    [InlineData(0, "", false)]
    public void ShouldValidateDotnetVersionEvidence_WhenExitCodeAndOutputChange(int exitCode, string output, bool expected)
    {
        IsValidDotnetVersionCommand(exitCode, output).Should().Be(expected);
    }

    [Theory]
    [InlineData(0, "8.0.418 [C:\\\\Program Files\\\\dotnet\\\\sdk]", true)]
    [InlineData(0, "7.0.404 [C:\\\\Program Files\\\\dotnet\\\\sdk]", false)]
    [InlineData(0, "9.0.100 [C:\\\\Program Files\\\\dotnet\\\\sdk]", false)]
    [InlineData(1, "8.0.418 [C:\\\\Program Files\\\\dotnet\\\\sdk]", false)]
    [InlineData(0, "", false)]
    public void ShouldDetectDotnet8Sdk_WhenSdkListOutputChanges(int exitCode, string output, bool expected)
    {
        HasDotnet8Sdk(exitCode, output).Should().Be(expected);
    }

    [Theory]
    [InlineData("C:\\tools\\Godot_v4.5.1-stable_mono_win64_console.exe", true)]
    [InlineData(".\\Godot_v4.5.1-stable_mono_win64_console.exe", false)]
    [InlineData("C:\\tools\\Godot_v4.5.1-stable_win64.exe", false)]
    [InlineData("", false)]
    public void ShouldValidateGodotBinContract_WhenPathChanges(string godotBinPath, bool expected)
    {
        IsValidGodotBinContract(godotBinPath).Should().Be(expected);
    }

    [Theory]
    [InlineData("Process", true)]
    [InlineData("User", true)]
    [InlineData("Machine", true)]
    [InlineData("Session", false)]
    [InlineData("", false)]
    public void ShouldValidateGodotBinEnvScope_WhenScopeChanges(string scope, bool expected)
    {
        IsValidGodotBinEnvScope(scope).Should().Be(expected);
    }

    [Theory]
    [InlineData("command", "dotnet_restore.command is required")]
    [InlineData("exit_code", "dotnet_restore.exit_code is required")]
    [InlineData("evidence_file", "dotnet_restore.evidence_file is required")]
    public void ShouldFailDotnetRestoreValidation_WhenRequiredKeyIsMissing(string missingKey, string expectedMessage)
    {
        var payload = missingKey switch
        {
            "command" => "{\"dotnet_restore\":{\"exit_code\":0,\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/dotnet-restore.txt\"}}",
            "exit_code" => "{\"dotnet_restore\":{\"command\":\"dotnet restore .\\\\NewRouge.sln\",\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/dotnet-restore.txt\"}}",
            _ => "{\"dotnet_restore\":{\"command\":\"dotnet restore .\\\\NewRouge.sln\",\"exit_code\":0}}",
        };

        var root = JsonDocument.Parse("{\"godot_commands\":{\"godot_version_command\":{\"command\":\"godot --version\",\"exit_code\":0,\"parsed_version\":\"4.5.1\",\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/godot-version.txt\"},\"godot_bin_version_command\":{\"command\":\"& $env:GODOT_BIN --version\",\"exit_code\":0,\"parsed_version\":\"4.5.1\",\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/godot-bin-version.txt\"}}," + payload[1..]).RootElement;

        root.TryGetProperty("dotnet_restore", out var dotnetRestore).Should().BeTrue();
        Action act = () => ValidateDotnetRestoreSection(dotnetRestore, FindRepoRoot());

        act.Should().Throw<Exception>().Where(ex => ex.Message.Contains(expectedMessage, StringComparison.OrdinalIgnoreCase));
    }

    [Theory]
    [InlineData("command", "godot_version_command.command is required")]
    [InlineData("exit_code", "godot_version_command.exit_code is required")]
    [InlineData("parsed_version", "godot_version_command.parsed_version is required")]
    [InlineData("evidence_file", "godot_version_command.evidence_file is required")]
    public void ShouldFailGodotCommandValidation_WhenRequiredKeyIsMissing(string missingKey, string expectedMessage)
    {
        var entryJson = missingKey switch
        {
            "command" => "{\"exit_code\":0,\"parsed_version\":\"4.5.1\",\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/godot-version.txt\"}",
            "exit_code" => "{\"command\":\"godot --version\",\"parsed_version\":\"4.5.1\",\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/godot-version.txt\"}",
            "parsed_version" => "{\"command\":\"godot --version\",\"exit_code\":0,\"evidence_file\":\"logs/ci/2026-02-15/env-evidence/godot-version.txt\"}",
            _ => "{\"command\":\"godot --version\",\"exit_code\":0,\"parsed_version\":\"4.5.1\"}",
        };

        using var document = JsonDocument.Parse("{\"godot_version_command\":" + entryJson + "}");
        var commands = document.RootElement;

        Action act = () => ValidateCommandEntry(commands, "godot_version_command", FindRepoRoot());
        act.Should().Throw<Exception>().Where(ex => ex.Message.Contains(expectedMessage, StringComparison.OrdinalIgnoreCase));
    }

    private static bool OutputContainsToken(string output, string token)
    {
        return !string.IsNullOrWhiteSpace(output)
               && output.Contains(token, StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsValidGodotCommandEvidence(int exitCode, string output)
    {
        return exitCode == 0 && OutputContainsToken(output, "4.5.1");
    }

    private static bool IsValidDotnetVersionCommand(int exitCode, string output)
    {
        if (exitCode != 0)
        {
            return false;
        }

        var firstLine = GetFirstNonEmptyLine(output);
        return !string.IsNullOrWhiteSpace(firstLine) && firstLine.StartsWith("8.", StringComparison.Ordinal);
    }

    private static bool HasDotnet8Sdk(int exitCode, string output)
    {
        if (exitCode != 0 || string.IsNullOrWhiteSpace(output))
        {
            return false;
        }

        var sdkVersions = output
            .Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(line => line.Trim())
            .Where(line => line.Length > 0)
            .Select(line => line.Split(' ', StringSplitOptions.RemoveEmptyEntries)[0])
            .ToArray();

        return sdkVersions.Any(version => version.StartsWith("8.", StringComparison.Ordinal));
    }

    private static bool IsValidGodotBinContract(string? godotBinPath)
    {
        if (string.IsNullOrWhiteSpace(godotBinPath))
        {
            return false;
        }

        if (!Path.IsPathRooted(godotBinPath))
        {
            return false;
        }

        var exeName = Path.GetFileName(godotBinPath);
        return ContainsToken(exeName, "mono") && ContainsToken(exeName, "console");
    }

    private static bool IsValidGodotBinEnvScope(string? scope)
    {
        if (string.IsNullOrWhiteSpace(scope))
        {
            return false;
        }

        return string.Equals(scope, "Process", StringComparison.OrdinalIgnoreCase)
               || string.Equals(scope, "User", StringComparison.OrdinalIgnoreCase)
               || string.Equals(scope, "Machine", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsSemanticEquivalentRestoreToNewRouge(string? command)
    {
        if (string.IsNullOrWhiteSpace(command))
        {
            return false;
        }

        var tokens = command.Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(token => token.Replace("\"", string.Empty).Trim())
            .ToArray();
        if (tokens.Length < 3)
        {
            return false;
        }

        if (!tokens[0].EndsWith("dotnet", StringComparison.OrdinalIgnoreCase) &&
            !tokens[0].EndsWith("dotnet.exe", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        if (!string.Equals(tokens[1], "restore", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var slnToken = tokens.Skip(2).FirstOrDefault(token => token.EndsWith(".sln", StringComparison.OrdinalIgnoreCase));
        if (string.IsNullOrWhiteSpace(slnToken))
        {
            return false;
        }

        var fileName = Path.GetFileName(slnToken.Replace("/", "\\"));
        return string.Equals(fileName, "NewRouge.sln", StringComparison.OrdinalIgnoreCase);
    }

    private static bool ContainsToken(string value, string token)
    {
        return value.Contains(token, StringComparison.OrdinalIgnoreCase);
    }

    private static string GetFirstNonEmptyLine(string output)
    {
        return output
            .Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(line => line.Trim())
            .FirstOrDefault(line => line.Length > 0) ?? string.Empty;
    }

    private static string FindRepoRoot()
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current is not null)
        {
            if (File.Exists(Path.Combine(current.FullName, "NewRouge.sln")))
            {
                return current.FullName;
            }

            current = current.Parent;
        }

        throw new InvalidOperationException("Unable to locate repository root containing NewRouge.sln.");
    }

    private static void ValidateGodotCommandEvidence(string taskJsonPath, string repoRoot, string expectedGodotBinPath)
    {
        using var document = JsonDocument.Parse(File.ReadAllText(taskJsonPath));
        var root = document.RootElement;

        root.TryGetProperty("godot_bin", out var godotBin).Should().BeTrue("task-0001.json must include godot_bin path");
        var godotBinPath = godotBin.GetString();
        godotBinPath.Should().NotBeNullOrWhiteSpace("task-0001.json must persist absolute GODOT_BIN path");
        Path.IsPathRooted(godotBinPath!).Should().BeTrue("task-0001.json must persist absolute GODOT_BIN path");
        godotBinPath.Should().Be(expectedGodotBinPath, "task-0001.json must preserve the current GODOT_BIN path");

        root.TryGetProperty("godot_bin_check", out var godotBinCheck).Should().BeTrue("task-0001.json must include godot_bin_check");
        godotBinCheck.TryGetProperty("installation_verification_result", out var installResult).Should().BeTrue("godot_bin_check.installation_verification_result is required");
        installResult.GetString().Should().Be("pass", "installation verification must pass for task 1");
        ValidateGodotBinEnv(root, repoRoot, expectedGodotBinPath);

        root.TryGetProperty("godot_commands", out var commands).Should().BeTrue("task-0001.json must include godot_commands");
        if (commands.TryGetProperty("godot_version_command", out _))
        {
            ValidateCommandEntry(commands, "godot_version_command", repoRoot);
        }
        ValidateCommandEntry(commands, "godot_bin_version_command", repoRoot);
    }

    private static void ValidateGodotBinEnv(JsonElement root, string repoRoot, string expectedGodotBinPath)
    {
        root.TryGetProperty("godot_bin_env", out var envInfo).Should().BeTrue("task-0001.json must include godot_bin_env");
        envInfo.TryGetProperty("env_var_name", out var envVarName).Should().BeTrue("godot_bin_env.env_var_name is required");
        envInfo.TryGetProperty("env_var_value", out var envVarValue).Should().BeTrue("godot_bin_env.env_var_value is required");
        envInfo.TryGetProperty("env_var_scope", out var envVarScope).Should().BeTrue("godot_bin_env.env_var_scope is required");
        envInfo.TryGetProperty("evidence_file", out var envEvidenceFile).Should().BeTrue("godot_bin_env.evidence_file is required");

        envVarName.GetString().Should().Be("GODOT_BIN");
        var envVarValueString = envVarValue.GetString();
        envVarValueString.Should().Be(expectedGodotBinPath);
        Path.IsPathRooted(envVarValueString!).Should().BeTrue("godot_bin_env.env_var_value must be absolute");
        IsValidGodotBinEnvScope(envVarScope.GetString()).Should().BeTrue("godot_bin_env.env_var_scope must be Process/User/Machine");

        var envEvidenceRelativePath = envEvidenceFile.GetString();
        envEvidenceRelativePath.Should().NotBeNullOrWhiteSpace("godot_bin_env.evidence_file must be populated");
        var envEvidenceAbsolutePath = Path.Combine(repoRoot, envEvidenceRelativePath!.Replace("/", Path.DirectorySeparatorChar.ToString()));
        File.Exists(envEvidenceAbsolutePath).Should().BeTrue("godot_bin_env.evidence_file must resolve to an existing file");
        var envEvidenceContent = File.ReadAllText(envEvidenceAbsolutePath);
        envEvidenceContent.Should().Contain("env_var_name=GODOT_BIN");
        envEvidenceContent.Should().Contain($"env_var_value={expectedGodotBinPath}");
    }

    private static void ValidateDotnetSdkEvidence(string taskJsonPath, string repoRoot)
    {
        using var document = JsonDocument.Parse(File.ReadAllText(taskJsonPath));
        var root = document.RootElement;

        root.TryGetProperty("dotnet_sdk_check", out var sdkCheck).Should().BeTrue("task-0001.json must include dotnet_sdk_check");
        sdkCheck.TryGetProperty("command", out var command).Should().BeTrue("dotnet_sdk_check.command is required");
        command.GetString().Should().Be("dotnet --list-sdks");

        sdkCheck.TryGetProperty("exit_code", out var exitCode).Should().BeTrue("dotnet_sdk_check.exit_code is required");
        exitCode.GetInt32().Should().Be(0, "dotnet --list-sdks must succeed");

        sdkCheck.TryGetProperty("has_dotnet8_sdk", out var hasDotnet8).Should().BeTrue("dotnet_sdk_check.has_dotnet8_sdk is required");
        hasDotnet8.GetBoolean().Should().BeTrue("dotnet --list-sdks must contain at least one 8.x SDK entry");

        sdkCheck.TryGetProperty("detected_sdk_versions", out var detectedVersions).Should().BeTrue("dotnet_sdk_check.detected_sdk_versions is required");
        detectedVersions.ValueKind.Should().Be(JsonValueKind.Array, "dotnet_sdk_check.detected_sdk_versions must be array");
        detectedVersions.EnumerateArray()
            .Select(item => item.GetString())
            .Where(item => !string.IsNullOrWhiteSpace(item))
            .Any(version => version!.StartsWith("8.", StringComparison.Ordinal))
            .Should()
            .BeTrue("detected_sdk_versions must include at least one 8.x entry");

        sdkCheck.TryGetProperty("evidence_file", out var evidenceFile).Should().BeTrue("dotnet_sdk_check.evidence_file is required");
        var evidenceRelativePath = evidenceFile.GetString();
        evidenceRelativePath.Should().NotBeNullOrWhiteSpace("dotnet_sdk_check.evidence_file must be populated");
        var evidenceAbsolutePath = Path.Combine(repoRoot, evidenceRelativePath!.Replace("/", Path.DirectorySeparatorChar.ToString()));
        File.Exists(evidenceAbsolutePath).Should().BeTrue("dotnet_sdk_check.evidence_file must resolve to existing file");
        var evidenceContent = File.ReadAllText(evidenceAbsolutePath);
        HasDotnet8Sdk(0, evidenceContent).Should().BeTrue("dotnet_sdk_check evidence file must include at least one 8.x SDK entry");
    }

    private static void ValidateDotnetRestoreSection(JsonElement dotnetRestore, string repoRoot)
    {
        dotnetRestore.TryGetProperty("command", out var command).Should().BeTrue("dotnet_restore.command is required");
        dotnetRestore.TryGetProperty("exit_code", out var exitCode).Should().BeTrue("dotnet_restore.exit_code is required");
        dotnetRestore.TryGetProperty("evidence_file", out var evidenceFile).Should().BeTrue("dotnet_restore.evidence_file is required");

        IsSemanticEquivalentRestoreToNewRouge(command.GetString()).Should().BeTrue(
            "dotnet_restore.command must semantically target NewRouge.sln using dotnet restore");
        exitCode.GetInt32().Should().Be(0, "dotnet restore must succeed for acceptance evidence");

        var evidenceRelativePath = evidenceFile.GetString();
        evidenceRelativePath.Should().NotBeNullOrWhiteSpace("dotnet_restore.evidence_file must be a relative artifact path");
        var evidenceAbsolutePath = Path.Combine(repoRoot, evidenceRelativePath!.Replace("/", Path.DirectorySeparatorChar.ToString()));
        File.Exists(evidenceAbsolutePath).Should().BeTrue("dotnet_restore.evidence_file must point to an existing artifact file");
    }

    private static void ValidateCommandEntry(JsonElement commands, string commandKey, string repoRoot)
    {
        commands.TryGetProperty(commandKey, out var entry).Should().BeTrue($"task-0001.json must include {commandKey}");
        entry.TryGetProperty("command", out _).Should().BeTrue($"{commandKey}.command is required");
        entry.TryGetProperty("exit_code", out var exitCode).Should().BeTrue($"{commandKey}.exit_code is required");
        entry.TryGetProperty("parsed_version", out var parsedVersion).Should().BeTrue($"{commandKey}.parsed_version is required");
        entry.TryGetProperty("evidence_file", out var evidenceFile).Should().BeTrue($"{commandKey}.evidence_file is required");

        var commandExitCode = exitCode.GetInt32();
        var parsedVersionValue = parsedVersion.GetString();
        IsValidGodotCommandEvidence(commandExitCode, parsedVersionValue ?? string.Empty).Should().BeTrue(
            $"{commandKey} must succeed and persist pinned 4.5.1 version");

        var commandValue = entry.TryGetProperty("command", out var commandElement) ? commandElement.GetString() : string.Empty;
        commandValue.Should().NotBeNullOrWhiteSpace($"{commandKey}.command must contain executable command text");
        if (string.Equals(commandKey, "godot_version_command", StringComparison.Ordinal))
        {
            commandValue.Should().Contain("godot --version");
        }
        else if (string.Equals(commandKey, "godot_bin_version_command", StringComparison.Ordinal))
        {
            commandValue.Should().Contain("$env:GODOT_BIN");
        }

        var evidenceRelativePath = evidenceFile.GetString();
        evidenceRelativePath.Should().NotBeNullOrWhiteSpace($"{commandKey}.evidence_file must be populated");
        var evidenceAbsolutePath = Path.Combine(repoRoot, evidenceRelativePath!.Replace("/", Path.DirectorySeparatorChar.ToString()));
        File.Exists(evidenceAbsolutePath).Should().BeTrue($"{commandKey}.evidence_file must resolve to an existing file");

        var evidenceContent = File.ReadAllText(evidenceAbsolutePath);
        IsValidGodotCommandEvidence(0, evidenceContent).Should().BeTrue(
            $"{commandKey}.evidence_file must include pinned Godot version output");
    }

    private static async Task<CommandResult> RunProcessAsync(string fileName, string arguments, string? prependPath = null)
    {
        try
        {
            var startInfo = new ProcessStartInfo
            {
                FileName = fileName,
                Arguments = arguments,
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                CreateNoWindow = true
            };

            if (!string.IsNullOrWhiteSpace(prependPath))
            {
                var currentPath = Environment.GetEnvironmentVariable("PATH") ?? string.Empty;
                startInfo.Environment["PATH"] = prependPath + ";" + currentPath;
            }

            using var process = Process.Start(startInfo);
            if (process is null)
            {
                return CommandResult.StartFailure(fileName, arguments, "Process.Start returned null.");
            }

            var stdOutTask = process.StandardOutput.ReadToEndAsync();
            var stdErrTask = process.StandardError.ReadToEndAsync();

            using var timeoutCts = new CancellationTokenSource(CommandTimeout);
            try
            {
                await process.WaitForExitAsync(timeoutCts.Token);
            }
            catch (OperationCanceledException)
            {
                try
                {
                    if (!process.HasExited)
                    {
                        process.Kill(entireProcessTree: true);
                    }
                }
                catch
                {
                }

                var timeoutStdOut = await stdOutTask;
                var timeoutStdErr = await stdErrTask;
                return new CommandResult(
                    -1,
                    timeoutStdOut,
                    timeoutStdErr,
                    fileName,
                    arguments,
                    $"Command exceeded timeout of {CommandTimeout.TotalSeconds:0} seconds.");
            }

            var stdOut = await stdOutTask;
            var stdErr = await stdErrTask;
            return new CommandResult(process.ExitCode, stdOut, stdErr, fileName, arguments, string.Empty);
        }
        catch (Exception ex)
        {
            return CommandResult.StartFailure(fileName, arguments, ex.Message);
        }
    }

    private sealed record CommandResult(
        int ExitCode,
        string StdOut,
        string StdErr,
        string FileName,
        string Arguments,
        string StartError)
    {
        public string DebugOutput =>
            $"Command: {FileName} {Arguments}{Environment.NewLine}" +
            $"ExitCode: {ExitCode}{Environment.NewLine}" +
            $"StartError: {(string.IsNullOrEmpty(StartError) ? "<none>" : StartError)}{Environment.NewLine}" +
            $"StdOut: {StdOut}{Environment.NewLine}" +
            $"StdErr: {StdErr}";

        public static CommandResult StartFailure(string fileName, string arguments, string startError)
        {
            return new CommandResult(
                -1,
                string.Empty,
                string.Empty,
                fileName,
                arguments,
                startError);
        }
    }
}
