using System;
using System.IO;
using System.Text.Json;
using FluentAssertions;
using Xunit;

namespace Game.Core.Tests.Tasks
{
    public sealed class Task1WindowsPlatformGateTests
    {
        private const string WindowsPlatform = "Windows";
        private const string TaskFileName = "task-0001.json";
        private const string OsPlatformProperty = "os_platform";
        private const string WindowsOnlyCheckProperty = "windows_only_check";
        private const string ResultProperty = "result";
        private const string PlatformEvidenceProperty = "platform_evidence";
        private const string EvidenceFileProperty = "evidence_file";
        private const string PassValue = "pass";

        // ACC:T1.13
        // ACC:T1.14
        [Fact]
        public void ShouldValidateRealTaskArtifact_WhenTask1PreflightHasRun()
        {
            var repoRoot = FindRepoRoot();
            var dateSegment = DateTime.UtcNow.ToString("yyyy-MM-dd");
            var taskJsonPath = Path.Combine(repoRoot, "logs", "ci", dateSegment, TaskFileName);

            File.Exists(taskJsonPath).Should().BeTrue("task-0001.json must be generated by Task1 preflight");
            var taskJson = File.ReadAllText(taskJsonPath);

            var gate = EvaluateWindowsOnlyGate(taskJson, evidencePath =>
            {
                var absolutePath = Path.Combine(repoRoot, evidencePath.Replace("/", Path.DirectorySeparatorChar.ToString()));
                if (!File.Exists(absolutePath))
                {
                    return (false, string.Empty);
                }

                return (true, File.ReadAllText(absolutePath));
            });
            gate.IsPass.Should().BeTrue(gate.Reason);
            gate.StopDownstream.Should().BeFalse();

            using var document = JsonDocument.Parse(taskJson);
            document.RootElement.GetProperty(OsPlatformProperty).GetString().Should().Be(WindowsPlatform);

            var windowsCheck = document.RootElement.GetProperty(WindowsOnlyCheckProperty);
            var evidencePath = windowsCheck.GetProperty(EvidenceFileProperty).GetString();
            evidencePath.Should().NotBeNullOrWhiteSpace("windows_only_check.evidence_file is required");
            var evidenceAbsolutePath = Path.Combine(repoRoot, evidencePath!.Replace("/", Path.DirectorySeparatorChar.ToString()));
            File.Exists(evidenceAbsolutePath).Should().BeTrue("windows_only_check.evidence_file must point to existing artifact");

            var platformEvidence = windowsCheck.GetProperty(PlatformEvidenceProperty).GetString();
            platformEvidence.Should().NotBeNullOrWhiteSpace("platform_evidence is required");

            var evidenceText = File.ReadAllText(evidenceAbsolutePath);
            evidenceText.Should().Contain("result=pass", "windows-only evidence must include explicit pass result");
            evidenceText.Should().Contain(platformEvidence!, "windows-only evidence must include platform_evidence value");
        }

        [Fact]
        public void ShouldPass_WhenPlatformIsWindowsAndEvidenceIsPresent()
        {
            var taskJson = JsonSerializer.Serialize(new
            {
                os_platform = "Windows",
                windows_only_check = new
                {
                    result = "pass",
                    platform_evidence = "Windows-11-22631",
                    evidence_file = "logs/ci/2026-02-15/env-evidence/windows-only-check.txt",
                },
            });

            var result = EvaluateWindowsOnlyGate(taskJson);

            result.IsPass.Should().BeTrue();
            result.StopDownstream.Should().BeFalse();
            result.Reason.Should().BeEmpty();
        }

        [Theory]
        [InlineData("Linux")]
        [InlineData("macOS")]
        [InlineData("")]
        public void ShouldFailAndStopDownstream_WhenOsPlatformIsNotWindows(string osPlatform)
        {
            var taskJson = JsonSerializer.Serialize(new
            {
                os_platform = osPlatform,
                windows_only_check = new
                {
                    result = "pass",
                    platform_evidence = "Host-Evidence",
                    evidence_file = "logs/ci/2026-02-15/env-evidence/windows-only-check.txt",
                },
            });

            var result = EvaluateWindowsOnlyGate(taskJson);

            result.IsPass.Should().BeFalse();
            result.StopDownstream.Should().BeTrue();
            result.Reason.Should().Contain("os_platform");
        }

        [Fact]
        public void ShouldFailAndStopDownstream_WhenOsPlatformIsMissing()
        {
            var taskJson = JsonSerializer.Serialize(new
            {
                windows_only_check = new
                {
                    result = "pass",
                    platform_evidence = "Windows-11-22631",
                    evidence_file = "logs/ci/2026-02-15/env-evidence/windows-only-check.txt",
                },
            });

            var result = EvaluateWindowsOnlyGate(taskJson);

            result.IsPass.Should().BeFalse();
            result.StopDownstream.Should().BeTrue();
            result.Reason.Should().Contain("os_platform");
        }

        [Fact]
        public void ShouldFailAndStopDownstream_WhenPlatformEvidenceIsMissing()
        {
            var taskJson = JsonSerializer.Serialize(new
            {
                os_platform = "Windows",
                windows_only_check = new
                {
                    result = "pass",
                    evidence_file = "logs/ci/2026-02-15/env-evidence/windows-only-check.txt",
                },
            });

            var result = EvaluateWindowsOnlyGate(taskJson);

            result.IsPass.Should().BeFalse();
            result.StopDownstream.Should().BeTrue();
            result.Reason.Should().Contain("platform evidence");
        }

        [Fact]
        public void ShouldFailAndStopDownstream_WhenResultIsNotPass()
        {
            var taskJson = JsonSerializer.Serialize(new
            {
                os_platform = "Windows",
                windows_only_check = new
                {
                    result = "fail",
                    platform_evidence = "Windows-11-22631",
                    evidence_file = "logs/ci/2026-02-15/env-evidence/windows-only-check.txt",
                },
            });

            var result = EvaluateWindowsOnlyGate(taskJson);

            result.IsPass.Should().BeFalse();
            result.StopDownstream.Should().BeTrue();
            result.Reason.Should().Contain("result");
        }

        [Fact]
        public void ShouldFailAndStopDownstream_WhenEvidenceFileIsMissing()
        {
            var taskJson = JsonSerializer.Serialize(new
            {
                os_platform = "Windows",
                windows_only_check = new
                {
                    result = "pass",
                    platform_evidence = "Windows-11-22631",
                },
            });

            var result = EvaluateWindowsOnlyGate(taskJson);

            result.IsPass.Should().BeFalse();
            result.StopDownstream.Should().BeTrue();
            result.Reason.Should().Contain("evidence_file");
        }

        [Fact]
        public void ShouldFailAndStopDownstream_WhenEvidenceFileDoesNotExist()
        {
            var taskJson = JsonSerializer.Serialize(new
            {
                os_platform = "Windows",
                windows_only_check = new
                {
                    result = "pass",
                    platform_evidence = "Windows-11-22631",
                    evidence_file = "logs/ci/2026-02-15/env-evidence/missing.txt",
                },
            });

            var result = EvaluateWindowsOnlyGate(taskJson, _ => (false, string.Empty));

            result.IsPass.Should().BeFalse();
            result.StopDownstream.Should().BeTrue();
            result.Reason.Should().Contain("evidence_file");
        }

        [Fact]
        public void ShouldFailAndStopDownstream_WhenEvidenceFileContentDoesNotContainPlatformEvidence()
        {
            var taskJson = JsonSerializer.Serialize(new
            {
                os_platform = "Windows",
                windows_only_check = new
                {
                    result = "pass",
                    platform_evidence = "Windows-11-22631",
                    evidence_file = "logs/ci/2026-02-15/env-evidence/windows-only-check.txt",
                },
            });

            var result = EvaluateWindowsOnlyGate(taskJson, _ => (true, "result=pass\nplatform=Windows-10\n"));

            result.IsPass.Should().BeFalse();
            result.StopDownstream.Should().BeTrue();
            result.Reason.Should().Contain("platform_evidence");
        }

        private static GateEvaluation EvaluateWindowsOnlyGate(
            string task0001Json,
            Func<string, (bool Exists, string Content)>? evidenceReader = null)
        {
            if (string.IsNullOrWhiteSpace(task0001Json))
            {
                return GateEvaluation.Fail(TaskFileName + " evidence is required.");
            }

            JsonDocument document;
            try
            {
                document = JsonDocument.Parse(task0001Json);
            }
            catch (JsonException)
            {
                return GateEvaluation.Fail(TaskFileName + " content is not valid JSON.");
            }

            using (document)
            {
                var osPlatform = document.RootElement.TryGetProperty(OsPlatformProperty, out var osPlatformElement)
                    ? osPlatformElement.GetString()
                    : null;
                if (!string.Equals(osPlatform, WindowsPlatform, StringComparison.OrdinalIgnoreCase))
                {
                    return GateEvaluation.Fail(OsPlatformProperty + " must be Windows.");
                }

                if (!document.RootElement.TryGetProperty(WindowsOnlyCheckProperty, out var checkElement) ||
                    checkElement.ValueKind != JsonValueKind.Object)
                {
                    return GateEvaluation.Fail(WindowsOnlyCheckProperty + " is required.");
                }

                var resultValue = checkElement.TryGetProperty(ResultProperty, out var resultElement)
                    ? resultElement.GetString()
                    : null;
                if (!string.Equals(resultValue, PassValue, StringComparison.OrdinalIgnoreCase))
                {
                    return GateEvaluation.Fail(WindowsOnlyCheckProperty + "." + ResultProperty + " must be pass.");
                }

                var evidence = checkElement.TryGetProperty(PlatformEvidenceProperty, out var evidenceElement)
                    ? evidenceElement.GetString()
                    : null;
                if (string.IsNullOrWhiteSpace(evidence))
                {
                    return GateEvaluation.Fail("platform evidence is required.");
                }

                var evidenceFile = checkElement.TryGetProperty(EvidenceFileProperty, out var evidenceFileElement)
                    ? evidenceFileElement.GetString()
                    : null;
                if (string.IsNullOrWhiteSpace(evidenceFile))
                {
                    return GateEvaluation.Fail("windows_only_check.evidence_file is required.");
                }

                if (evidenceReader is not null)
                {
                    var evidenceResult = evidenceReader(evidenceFile);
                    if (!evidenceResult.Exists)
                    {
                        return GateEvaluation.Fail("windows_only_check.evidence_file does not exist.");
                    }

                    if (!evidenceResult.Content.Contains(evidence, StringComparison.OrdinalIgnoreCase))
                    {
                        return GateEvaluation.Fail("windows_only_check.evidence_file must contain platform_evidence.");
                    }
                }
            }

            return GateEvaluation.Pass();
        }

        private static string FindRepoRoot()
        {
            var current = new DirectoryInfo(AppContext.BaseDirectory);
            while (current is not null)
            {
                if (File.Exists(Path.Combine(current.FullName, "NewRouge.sln")))
                {
                    return current.FullName;
                }

                current = current.Parent;
            }

            throw new InvalidOperationException("Unable to locate repository root containing NewRouge.sln.");
        }

        private sealed class GateEvaluation
        {
            private GateEvaluation(bool isPass, bool stopDownstream, string reason)
            {
                IsPass = isPass;
                StopDownstream = stopDownstream;
                Reason = reason;
            }

            public bool IsPass { get; }

            public bool StopDownstream { get; }

            public string Reason { get; }

            public static GateEvaluation Pass()
            {
                return new GateEvaluation(true, false, string.Empty);
            }

            public static GateEvaluation Fail(string reason)
            {
                return new GateEvaluation(false, true, reason);
            }
        }
    }
}
